GET http://localhost:3003/api/user
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImV6cmEiLCJpZCI6IjViY2RkN2RjODNkYzcwMjQ2YTBkODc5ZCIsImlhdCI6MTU0MDIxODYxMH0.wOtY1w8CBCEN_5p7DU5zZgw421E6_RtGcS1vUni7uAo
